name = "age"
description = "Minimal, multi-architecture OCI container image for age file encryption"
version = "1.3.2"

upstream = "FiloSottile/age"
license = "BSD-3-Clause"

architectures = ["amd64", "arm64"]

[platform.amd64]
target = "linux-amd64"
sha256 = "cbe24006683f8eb669266162894b9a522a1af52f2665fbc63a4bb032ed26ac10"

[platform.arm64]
target = "linux-arm64"
sha256 = "6b8dc4333c53a5a57c9e5834e3a48f92605d7154014cd07269ff3327db5d37f4"
